# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84313cfc1a997e9150d1ab4500d330c7c340d5eac602ec21cfba517b8c6335b69ed4be000602731f98610a1bfccac782733e64056f98c07d0494f8ca8c7c794b

test:
  secret_key_base: 9e3b16c0b67c4ac09089746d96add25fb861484600e3acc06e087fa2fa2cd303324f8f45bf6a263228050e9c34ad56d379679438ca76bccc28ba2f8e1f964194

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
